### ISSUE TITLE
Colorful output

### ISSUE THREAD

**Issue by pesarkhobeee** [martinohmann/dts#5]
That would be nice if the standard output could be also colorful like
https://github.com/felixfbecker/cli-highlight

**Comment by martinohmann** [comment]
Hey @pesarkhobeee, I hacked together a first implementation for colored output in #6. If you are interested you can try it out and let me know what you think.

One problem with colorful output is that it `dts` will get very slow in situations where the output is very large as there is a lot of parsing work involved for the syntax highlighting. But for these cases you could then use `--color=never` to disable output coloring.

**Comment by pesarkhobeee** [comment]
@martinohmann Sadly I couldn't compile it, you can see the error message in the picture 

<img width="1413" alt="Screenshot 2021-12-23 at 16 48 07" src="https://user-images.githubusercontent.com/147461/147263454-78e8187b-429d-4b78-a77d-0f635e1c38d2.png">

My idea was feeding it via below command and see how colors and transformation to the YAML format will work:

`docker run --rm -v $HOME/Library/Caches:/root/.cache/ aquasec/trivy:0.18.3 --ignore-unfixed --severity CRITICAL --vuln-type library --format json  docker.bintray.io/jfrog/artifactory-oss:6.8.7 > transfer_this_json_yaml_with_dts.json`

**Comment by martinohmann** [comment]
@pesarkhobeee The was an issue with the `clap` dependency which i'm currently using in `3.0.0-rc-*` since the `3.0.0` is not out yet. They seem to have changed some APIs in the most recent release candidate.

I pushed a fix and rebased the PR, it should build correctly now.

**Comment by pesarkhobeee** [comment]
@martinohmann thanks, I tested it and it seems everything is correct and fast :)
<img width="1552" alt="Screenshot 2021-12-23 at 17 30 26" src="https://user-images.githubusercontent.com/147461/147268120-79531b46-5e60-4380-8106-94fb3bb0fdb8.png">

**Comment by pesarkhobeee** [comment]
I was thinking about two opinions, maybe changing the default color them to something like "Github" will give a better first impression to the users. the other opinion is supporting pagination because if I use `less` or `more` commands I am not able to see the output colorful anymore!

**Comment by martinohmann** [comment]
1. Using `GitHub` as a default theme is not very sensible I think. It only works well with terminals that have a light background and becomes hard to read on dark backgrounds. I'll go with `base16` as a default for now as it's a good middle ground. If you prefer `GitHub`, just set it globally via `DTS_THEME=GitHub`.
2. If `dts` is piped it will not emit colors with the linked PR with `--color auto` which is the default. You have to force color for that by setting `DTS_COLOR=always` or via CLI arg:
    ```
    dts tests/fixtures/example.json --color always | less
    ```
3. I may add pagination but not as part of this issue.

**Comment by pesarkhobeee** [comment]
thanks a lot @martinohmann, like always it was informative, would be nice if we have this kind of examples in the readme and man page too :)

**Comment by martinohmann** [comment]
I think the initial implementation of colored output is in a good enough state for now, so I merged #6.
